### PR TITLE
Fixed the overflow bug

### PR DESCRIPTION
**Pull request by r-arvind**
I found a simple hack to fix the overflow bug. Also, I have made it so that the scroll bar is not visible.

### CODE REVIEW

**Comment by shrey183** [comment]
This is great! However, we still cannot see the extra text. Do you think its possible to show all the text without overflow?

**Comment by r-arvind** [comment]
There are two things we can do:
1. To wrap the overflowing content so that it goes to the next line
2. To scale down the size of the text depending on the size of overflowing content.

Which one would you prefer ?

**Comment by shrey183** [comment]
I would prefer if you implemented, scaling down the size of the text. Try it, if you come across any issues, post them here.

**Comment by r-arvind** [comment]
@shrey183, I am busy with some other work. You can expect a PR for this issue by the end of this week.

**Pull request merged**
